<?php
/**
 * Idpv2SAMLBinding
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Management API
 *
 * The management API is as the name states the interface where systems can mutate IAM objects like organizations, projects, clients, users and so on if they have the necessary access rights.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArthurHlt\Zitadel\Model;
use \ArthurHlt\Zitadel\ObjectSerializer;

/**
 * Idpv2SAMLBinding Class Doc Comment
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Idpv2SAMLBinding
{
    /**
     * Possible values of this enum
     */
    public const SAML_BINDING_UNSPECIFIED = 'SAML_BINDING_UNSPECIFIED';

    public const SAML_BINDING_POST = 'SAML_BINDING_POST';

    public const SAML_BINDING_REDIRECT = 'SAML_BINDING_REDIRECT';

    public const SAML_BINDING_ARTIFACT = 'SAML_BINDING_ARTIFACT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SAML_BINDING_UNSPECIFIED,
            self::SAML_BINDING_POST,
            self::SAML_BINDING_REDIRECT,
            self::SAML_BINDING_ARTIFACT
        ];
    }
}


