<?php
/**
 * Idpv1AzureADTenantType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Management API
 *
 * The management API is as the name states the interface where systems can mutate IAM objects like organizations, projects, clients, users and so on if they have the necessary access rights.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArthurHlt\Zitadel\Model;
use \ArthurHlt\Zitadel\ObjectSerializer;

/**
 * Idpv1AzureADTenantType Class Doc Comment
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Idpv1AzureADTenantType
{
    /**
     * Possible values of this enum
     */
    public const AZURE_AD_TENANT_TYPE_COMMON = 'AZURE_AD_TENANT_TYPE_COMMON';

    public const AZURE_AD_TENANT_TYPE_ORGANISATIONS = 'AZURE_AD_TENANT_TYPE_ORGANISATIONS';

    public const AZURE_AD_TENANT_TYPE_CONSUMERS = 'AZURE_AD_TENANT_TYPE_CONSUMERS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AZURE_AD_TENANT_TYPE_COMMON,
            self::AZURE_AD_TENANT_TYPE_ORGANISATIONS,
            self::AZURE_AD_TENANT_TYPE_CONSUMERS
        ];
    }
}


