<?php
/**
 * V1AddOrgOIDCIDPRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Management API
 *
 * The management API is as the name states the interface where systems can mutate IAM objects like organizations, projects, clients, users and so on if they have the necessary access rights.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArthurHlt\Zitadel\Model;

use \ArrayAccess;
use \ArthurHlt\Zitadel\ObjectSerializer;

/**
 * V1AddOrgOIDCIDPRequest Class Doc Comment
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1AddOrgOIDCIDPRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'v1AddOrgOIDCIDPRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'stylingType' => '\ArthurHlt\Zitadel\Model\V1IDPStylingType',
        'clientId' => 'string',
        'clientSecret' => 'string',
        'issuer' => 'string',
        'scopes' => 'string[]',
        'displayNameMapping' => '\ArthurHlt\Zitadel\Model\V1OIDCMappingField',
        'usernameMapping' => '\ArthurHlt\Zitadel\Model\V1OIDCMappingField',
        'autoRegister' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'stylingType' => null,
        'clientId' => null,
        'clientSecret' => null,
        'issuer' => null,
        'scopes' => null,
        'displayNameMapping' => null,
        'usernameMapping' => null,
        'autoRegister' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'stylingType' => false,
        'clientId' => false,
        'clientSecret' => false,
        'issuer' => false,
        'scopes' => false,
        'displayNameMapping' => false,
        'usernameMapping' => false,
        'autoRegister' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'stylingType' => 'stylingType',
        'clientId' => 'clientId',
        'clientSecret' => 'clientSecret',
        'issuer' => 'issuer',
        'scopes' => 'scopes',
        'displayNameMapping' => 'displayNameMapping',
        'usernameMapping' => 'usernameMapping',
        'autoRegister' => 'autoRegister'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'stylingType' => 'setStylingType',
        'clientId' => 'setClientId',
        'clientSecret' => 'setClientSecret',
        'issuer' => 'setIssuer',
        'scopes' => 'setScopes',
        'displayNameMapping' => 'setDisplayNameMapping',
        'usernameMapping' => 'setUsernameMapping',
        'autoRegister' => 'setAutoRegister'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'stylingType' => 'getStylingType',
        'clientId' => 'getClientId',
        'clientSecret' => 'getClientSecret',
        'issuer' => 'getIssuer',
        'scopes' => 'getScopes',
        'displayNameMapping' => 'getDisplayNameMapping',
        'usernameMapping' => 'getUsernameMapping',
        'autoRegister' => 'getAutoRegister'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('stylingType', $data ?? [], null);
        $this->setIfExists('clientId', $data ?? [], null);
        $this->setIfExists('clientSecret', $data ?? [], null);
        $this->setIfExists('issuer', $data ?? [], null);
        $this->setIfExists('scopes', $data ?? [], null);
        $this->setIfExists('displayNameMapping', $data ?? [], null);
        $this->setIfExists('usernameMapping', $data ?? [], null);
        $this->setIfExists('autoRegister', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 200)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 200.";
        }

        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['clientId'] === null) {
            $invalidProperties[] = "'clientId' can't be null";
        }
        if ((mb_strlen($this->container['clientId']) > 200)) {
            $invalidProperties[] = "invalid value for 'clientId', the character length must be smaller than or equal to 200.";
        }

        if ((mb_strlen($this->container['clientId']) < 1)) {
            $invalidProperties[] = "invalid value for 'clientId', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['clientSecret'] === null) {
            $invalidProperties[] = "'clientSecret' can't be null";
        }
        if ((mb_strlen($this->container['clientSecret']) > 200)) {
            $invalidProperties[] = "invalid value for 'clientSecret', the character length must be smaller than or equal to 200.";
        }

        if ((mb_strlen($this->container['clientSecret']) < 1)) {
            $invalidProperties[] = "invalid value for 'clientSecret', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['issuer'] === null) {
            $invalidProperties[] = "'issuer' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 200)) {
            throw new \InvalidArgumentException('invalid length for $name when calling V1AddOrgOIDCIDPRequest., must be smaller than or equal to 200.');
        }
        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling V1AddOrgOIDCIDPRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets stylingType
     *
     * @return \ArthurHlt\Zitadel\Model\V1IDPStylingType|null
     */
    public function getStylingType()
    {
        return $this->container['stylingType'];
    }

    /**
     * Sets stylingType
     *
     * @param \ArthurHlt\Zitadel\Model\V1IDPStylingType|null $stylingType stylingType
     *
     * @return self
     */
    public function setStylingType($stylingType)
    {
        if (is_null($stylingType)) {
            throw new \InvalidArgumentException('non-nullable stylingType cannot be null');
        }
        $this->container['stylingType'] = $stylingType;

        return $this;
    }

    /**
     * Gets clientId
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['clientId'];
    }

    /**
     * Sets clientId
     *
     * @param string $clientId client id generated by the identity provider
     *
     * @return self
     */
    public function setClientId($clientId)
    {
        if (is_null($clientId)) {
            throw new \InvalidArgumentException('non-nullable clientId cannot be null');
        }
        if ((mb_strlen($clientId) > 200)) {
            throw new \InvalidArgumentException('invalid length for $clientId when calling V1AddOrgOIDCIDPRequest., must be smaller than or equal to 200.');
        }
        if ((mb_strlen($clientId) < 1)) {
            throw new \InvalidArgumentException('invalid length for $clientId when calling V1AddOrgOIDCIDPRequest., must be bigger than or equal to 1.');
        }

        $this->container['clientId'] = $clientId;

        return $this;
    }

    /**
     * Gets clientSecret
     *
     * @return string
     */
    public function getClientSecret()
    {
        return $this->container['clientSecret'];
    }

    /**
     * Sets clientSecret
     *
     * @param string $clientSecret client secret generated by the identity provider
     *
     * @return self
     */
    public function setClientSecret($clientSecret)
    {
        if (is_null($clientSecret)) {
            throw new \InvalidArgumentException('non-nullable clientSecret cannot be null');
        }
        if ((mb_strlen($clientSecret) > 200)) {
            throw new \InvalidArgumentException('invalid length for $clientSecret when calling V1AddOrgOIDCIDPRequest., must be smaller than or equal to 200.');
        }
        if ((mb_strlen($clientSecret) < 1)) {
            throw new \InvalidArgumentException('invalid length for $clientSecret when calling V1AddOrgOIDCIDPRequest., must be bigger than or equal to 1.');
        }

        $this->container['clientSecret'] = $clientSecret;

        return $this;
    }

    /**
     * Gets issuer
     *
     * @return string
     */
    public function getIssuer()
    {
        return $this->container['issuer'];
    }

    /**
     * Sets issuer
     *
     * @param string $issuer the OIDC issuer of the identity provider
     *
     * @return self
     */
    public function setIssuer($issuer)
    {
        if (is_null($issuer)) {
            throw new \InvalidArgumentException('non-nullable issuer cannot be null');
        }
        $this->container['issuer'] = $issuer;

        return $this;
    }

    /**
     * Gets scopes
     *
     * @return string[]|null
     */
    public function getScopes()
    {
        return $this->container['scopes'];
    }

    /**
     * Sets scopes
     *
     * @param string[]|null $scopes the scopes requested by ZITADEL during the request on the identity provider
     *
     * @return self
     */
    public function setScopes($scopes)
    {
        if (is_null($scopes)) {
            throw new \InvalidArgumentException('non-nullable scopes cannot be null');
        }
        $this->container['scopes'] = $scopes;

        return $this;
    }

    /**
     * Gets displayNameMapping
     *
     * @return \ArthurHlt\Zitadel\Model\V1OIDCMappingField|null
     */
    public function getDisplayNameMapping()
    {
        return $this->container['displayNameMapping'];
    }

    /**
     * Sets displayNameMapping
     *
     * @param \ArthurHlt\Zitadel\Model\V1OIDCMappingField|null $displayNameMapping displayNameMapping
     *
     * @return self
     */
    public function setDisplayNameMapping($displayNameMapping)
    {
        if (is_null($displayNameMapping)) {
            throw new \InvalidArgumentException('non-nullable displayNameMapping cannot be null');
        }
        $this->container['displayNameMapping'] = $displayNameMapping;

        return $this;
    }

    /**
     * Gets usernameMapping
     *
     * @return \ArthurHlt\Zitadel\Model\V1OIDCMappingField|null
     */
    public function getUsernameMapping()
    {
        return $this->container['usernameMapping'];
    }

    /**
     * Sets usernameMapping
     *
     * @param \ArthurHlt\Zitadel\Model\V1OIDCMappingField|null $usernameMapping usernameMapping
     *
     * @return self
     */
    public function setUsernameMapping($usernameMapping)
    {
        if (is_null($usernameMapping)) {
            throw new \InvalidArgumentException('non-nullable usernameMapping cannot be null');
        }
        $this->container['usernameMapping'] = $usernameMapping;

        return $this;
    }

    /**
     * Gets autoRegister
     *
     * @return bool|null
     */
    public function getAutoRegister()
    {
        return $this->container['autoRegister'];
    }

    /**
     * Sets autoRegister
     *
     * @param bool|null $autoRegister autoRegister
     *
     * @return self
     */
    public function setAutoRegister($autoRegister)
    {
        if (is_null($autoRegister)) {
            throw new \InvalidArgumentException('non-nullable autoRegister cannot be null');
        }
        $this->container['autoRegister'] = $autoRegister;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


