<?php
/**
 * V1DomainFieldName
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Management API
 *
 * The management API is as the name states the interface where systems can mutate IAM objects like organizations, projects, clients, users and so on if they have the necessary access rights.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArthurHlt\Zitadel\Model;
use \ArthurHlt\Zitadel\ObjectSerializer;

/**
 * V1DomainFieldName Class Doc Comment
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1DomainFieldName
{
    /**
     * Possible values of this enum
     */
    public const DOMAIN_FIELD_NAME_UNSPECIFIED = 'DOMAIN_FIELD_NAME_UNSPECIFIED';

    public const DOMAIN_FIELD_NAME_DOMAIN = 'DOMAIN_FIELD_NAME_DOMAIN';

    public const DOMAIN_FIELD_NAME_PRIMARY = 'DOMAIN_FIELD_NAME_PRIMARY';

    public const DOMAIN_FIELD_NAME_GENERATED = 'DOMAIN_FIELD_NAME_GENERATED';

    public const DOMAIN_FIELD_NAME_CREATION_DATE = 'DOMAIN_FIELD_NAME_CREATION_DATE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DOMAIN_FIELD_NAME_UNSPECIFIED,
            self::DOMAIN_FIELD_NAME_DOMAIN,
            self::DOMAIN_FIELD_NAME_PRIMARY,
            self::DOMAIN_FIELD_NAME_GENERATED,
            self::DOMAIN_FIELD_NAME_CREATION_DATE
        ];
    }
}


