<?php
/**
 * V3alphaExecutionType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Management API
 *
 * The management API is as the name states the interface where systems can mutate IAM objects like organizations, projects, clients, users and so on if they have the necessary access rights.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArthurHlt\Zitadel\Model;
use \ArthurHlt\Zitadel\ObjectSerializer;

/**
 * V3alphaExecutionType Class Doc Comment
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V3alphaExecutionType
{
    /**
     * Possible values of this enum
     */
    public const EXECUTION_TYPE_UNSPECIFIED = 'EXECUTION_TYPE_UNSPECIFIED';

    public const EXECUTION_TYPE_REQUEST = 'EXECUTION_TYPE_REQUEST';

    public const EXECUTION_TYPE_RESPONSE = 'EXECUTION_TYPE_RESPONSE';

    public const EXECUTION_TYPE_EVENT = 'EXECUTION_TYPE_EVENT';

    public const EXECUTION_TYPE_FUNCTION = 'EXECUTION_TYPE_FUNCTION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EXECUTION_TYPE_UNSPECIFIED,
            self::EXECUTION_TYPE_REQUEST,
            self::EXECUTION_TYPE_RESPONSE,
            self::EXECUTION_TYPE_EVENT,
            self::EXECUTION_TYPE_FUNCTION
        ];
    }
}


