<?php
/**
 * BrandingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Management API
 *
 * The management API is as the name states the interface where systems can mutate IAM objects like organizations, projects, clients, users and so on if they have the necessary access rights.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ArthurHlt\Zitadel\Test\Api;

use \ArthurHlt\Zitadel\Configuration;
use \ArthurHlt\Zitadel\ApiException;
use \ArthurHlt\Zitadel\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BrandingApiTest Class Doc Comment
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BrandingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for adminServiceActivateLabelPolicy
     *
     * Activate Labeling/Branding Settings.
     *
     */
    public function testAdminServiceActivateLabelPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminServiceGetPreviewLabelPolicy
     *
     * Get Preview Private Labeling/Branding Settings.
     *
     */
    public function testAdminServiceGetPreviewLabelPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminServiceRemoveLabelPolicyFont
     *
     * Remove Font.
     *
     */
    public function testAdminServiceRemoveLabelPolicyFont()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminServiceRemoveLabelPolicyIcon
     *
     * Remove Icon Light.
     *
     */
    public function testAdminServiceRemoveLabelPolicyIcon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminServiceRemoveLabelPolicyIconDark
     *
     * Remove Icon Dark.
     *
     */
    public function testAdminServiceRemoveLabelPolicyIconDark()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminServiceRemoveLabelPolicyLogo
     *
     * Remove Logo Light.
     *
     */
    public function testAdminServiceRemoveLabelPolicyLogo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminServiceRemoveLabelPolicyLogoDark
     *
     * Remove Logo Dark.
     *
     */
    public function testAdminServiceRemoveLabelPolicyLogoDark()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminServiceUpdateLabelPolicy
     *
     * Update Labeling/Branding Settings.
     *
     */
    public function testAdminServiceUpdateLabelPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceAddCustomLabelPolicy
     *
     * Create Labeling/Branding Settings.
     *
     */
    public function testManagementServiceAddCustomLabelPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceGetDefaultLabelPolicy
     *
     * Get Default Private Labeling/Branding Settings.
     *
     */
    public function testManagementServiceGetDefaultLabelPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceResetLabelPolicyToDefault
     *
     * Reset Labeling/Branding Settings.
     *
     */
    public function testManagementServiceResetLabelPolicyToDefault()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
