<?php
/**
 * ProjectsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Management API
 *
 * The management API is as the name states the interface where systems can mutate IAM objects like organizations, projects, clients, users and so on if they have the necessary access rights.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hi@zitadel.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ArthurHlt\Zitadel\Test\Api;

use \ArthurHlt\Zitadel\Configuration;
use \ArthurHlt\Zitadel\ApiException;
use \ArthurHlt\Zitadel\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ArthurHlt\Zitadel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProjectsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for managementServiceAddProject
     *
     * Create Project.
     *
     */
    public function testManagementServiceAddProject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceAddProjectMember
     *
     * Add Project Member.
     *
     */
    public function testManagementServiceAddProjectMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceDeactivateProject
     *
     * Deactivate Project.
     *
     */
    public function testManagementServiceDeactivateProject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceGetGrantedProjectByID
     *
     * Get Granted Project By ID.
     *
     */
    public function testManagementServiceGetGrantedProjectByID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceGetProjectByID
     *
     * Get Project By ID.
     *
     */
    public function testManagementServiceGetProjectByID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceGetProjectGrantByID
     *
     * Project Grant By ID.
     *
     */
    public function testManagementServiceGetProjectGrantByID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceListGrantedProjectRoles
     *
     * Search Granted Project Roles.
     *
     */
    public function testManagementServiceListGrantedProjectRoles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceListGrantedProjects
     *
     * Search Granted Project.
     *
     */
    public function testManagementServiceListGrantedProjects()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceListProjectChanges
     *
     * Project History.
     *
     */
    public function testManagementServiceListProjectChanges()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceListProjectGrantChanges
     *
     * Project Grant History.
     *
     */
    public function testManagementServiceListProjectGrantChanges()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceListProjectMemberRoles
     *
     * List Project Member Roles.
     *
     */
    public function testManagementServiceListProjectMemberRoles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceListProjectMembers
     *
     * List Project Members.
     *
     */
    public function testManagementServiceListProjectMembers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceListProjects
     *
     * Search Project.
     *
     */
    public function testManagementServiceListProjects()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceReactivateProject
     *
     * Reactivate Project.
     *
     */
    public function testManagementServiceReactivateProject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceRemoveProject
     *
     * Remove Project.
     *
     */
    public function testManagementServiceRemoveProject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceRemoveProjectMember
     *
     * Remove Project Member.
     *
     */
    public function testManagementServiceRemoveProjectMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceUpdateProject
     *
     * Update Project.
     *
     */
    public function testManagementServiceUpdateProject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for managementServiceUpdateProjectMember
     *
     * Update Project Member.
     *
     */
    public function testManagementServiceUpdateProjectMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
